import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { getSession, signOut, useSession } from "next-auth/react";
import { useRouter } from "next/router";
import Notes from "./notes";
import { Container, Group, Header, Navbar, Paper } from "@mantine/core";
import { getNotes } from "@/util/mongoFunctions";
import { connectToDatabase } from "@/util/mongodb";
/* import { HeaderComponent } from "@/components/shared/Header";
 */
export default function Home({ fetchedNotes }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*       <HeaderComponent/>
       */}{" "}
      <Container fluid={true}>
        <Notes fetchedNotes={fetchedNotes}></Notes>
      </Container>
    </>
  );
}
export async function getServerSideProps(context) {
  //console.log(contextte)
  let session = await getSession(context);
  console.log(session);
  if (session === null || session == undefined) {
    return {
      redirect: {
        permanent: false,
        destination: "/signin",
      },
    };
  }
  connectToDatabase();
  let fetchedNotes = await getNotes(session.user._id);
  return { props: { fetchedNotes: JSON.parse(JSON.stringify(fetchedNotes)) } };
}
